### ISSUE TITLE
I can correlate a message without process instance id

### ISSUE THREAD

**Issue by meyerdan** [camunda/camunda-engine-cassandra#3]
Currently it is only possible to correlate a message if the process instance id is provided.

AT:
- I don't have to provide a process instance id when correlating a message.
- I can use businessKey and or variables

Example:

``` java
    runtimeService.createMessageCorrelation("stop")
      .processInstanceVariableEquals(...)
      .processInstanceBusinessKey(...)
      .correlateAll();
```

**Comment by natalia-levine** [comment]
now can correlate on any combination of executionId, processId, business key and event name and type, still need to do the variables

**Comment by natalia-levine** [comment]
Variables added as well
